### PR TITLE
fix: access token too big for h3 session

### PR DESCRIPTION
**Pull request by Marlight**
Fixes the problem from issue #20 that the access token becomes too large for the h3 session and thus creates a login loop.

### CODE REVIEW

**Comment by gheithen** [comment]
@Marlight I've tred going with this approach in a forked version of the repository. Do you have any issue with your persistent user session 'disappearing'? on occassion I get the 'persistent user session not found' and then I need to refresh the browser.
PS. I think you need to set the persistent session  in the callback event handler in 'server/handler/callback.ts' too.

**Comment by raj-saroj-vst-au4** [comment]
How do i reproduce this ? @gheithen

**Comment by itpropro** [comment]
This just removes the feature to expose the access token, when the real issue lies in how the access token is used. The access token should not contain any more information than what is necessary to authenticate the user and maybe add some additional claims. 
If the access token is too big to fit inside of a cookie, there is a very high probability of the token containing data like user information that should be collected from another place.

**Comment by itpropro** [comment]
@Marlight 0.17.0 introduced token handling that doesn't use the session cookie anymore.

**Pull request closed without merging**
